// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from "@/components/Providers"; 
import { AlertProvider } from "@/components/providers/AlertProvider";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Slip Vision",
  description: "ระบบตรวจสอบสลิปโอนเงินด้วย AI Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ 2. ต้องเอา Providers (NextAuth) มาครอบเป็นชั้นนอกสุด หรือครอบ AlertProvider อีกที */}
        <Providers>
          <AlertProvider>
            <Toaster />
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {children}
            </ThemeProvider>
          </AlertProvider>
        </Providers>
      </body>
    </html>
  );
}